Feature: not just utc time but also support other timezone by setting in prefs page
swsnr/gnome-shell-extension-utc-clock pull request #2
Opened 2023-11-15 11:22 UTC by ChasingZenith

2023-11-15 12:01 UTC, swsnr commented
I'm not sure I'd like to merge this.  I feel like it's out of scope for this extension, and I have no use case for this feature.

2023-11-15 14:13 UTC, swsnr requested changes
Not promising to merge it even though, but for me to even consider it, please address the following points:

- Address all remarks in this review.
- Fix the error on Github actions.
- Rebase onto master and move the new settings UI into the blueprint template.

2023-11-15 14:13 UTC, swsnr commented on src/extension.ts
> +    const now = GLib.DateTime.new_now_utc().add_hours(this.settings.get_int("utc-offset"));
That's definitely not the right way to handle timezone offsets; in particular format codes such as `%z` will be entirely unaware if you apply the offset this way.

You need to create a date time object with proper offset information attached.

2023-11-15 14:13 UTC, swsnr commented on src/prefs.ts
> +          upper: 14,
Where do these limits come from?

2023-11-15 14:13 UTC, swsnr commented on schemas/org.gnome.shell.extensions.swsnr-utc-clock.gschema.xml
> +      <description>A int32 which describes the offet of the time zone in hours</description>
The type information is entirely redundant here; just write  "A valid offset from UTC" as summary, and omit the description.

2023-11-15 18:10 UTC, ChasingZenith commented
Thank you for your kindly review! What you point out is completely helpful. Sorry for the bad quality since it is my first touch to gtk, gnome extension, so I am not very familiar with it. I will try to solve this some days later, since I am quite busy this week.

2023-12-01 07:21 UTC, swsnr commented
@ChasingZenith Do you still intend to work on this?  If I don't hear anything from you, I'll close this in a few days.

2023-12-01 10:42 UTC, ChasingZenith commented
Sorry, I'll work on this some times later. Please close it for the moment.

2023-12-01 10:42 UTC, closed without merging